import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Relationship goals{" <3"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-3xl text-center">Hello World!</section>
    </div>
  );
}
